import sqlite3
from ast import literal_eval

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Connecting to the data source, creating dataframes for each table
connection = sqlite3.connect("data/sample.sqlite")
account = pd.read_sql_query('select * from account', connection)
iap_purchase = pd.read_sql_query('select * from iap_purchase', connection)

# Deleting null values from the dataframe because they would conflict when mapping the country names
account.dropna(inplace=True)

# Importing dictionary of 'country_code':'country_name'
with open('data/country_names.json', 'r') as f:
    countries_data = literal_eval(f.read())
account['country_name'] = [countries_data[k] for k in account['country_code']]

# Merging data from account to iap_purchase using account_id key (equal to SQL Left (Outer) Join)
revenue_per_country = pd.merge(iap_purchase,
                               account,
                               on='account_id',
                               how='left')

# Deleting null values from the dataframe because they would conflict in the plot
revenue_per_country.dropna(inplace=True)

# Converting cents to USD
revenue_per_country['iap_price_usd_cents'] = revenue_per_country['iap_price_usd_cents'] / 100.

# Grouping data by country_name and summing sales made in each country throughout the year + sorting
revenue_per_country = revenue_per_country.groupby('country_name')['iap_price_usd_cents'].sum()
revenue_per_country = revenue_per_country.reset_index()
revenue_per_country = revenue_per_country.sort_values(by='iap_price_usd_cents', ascending=False)

# Plot with geographical split of total revenue of users
# locations - each country recorded in country_names column
# z - total amounts of revenue in each country in USD
map_data = go.Figure(go.Choropleth(
    locations=revenue_per_country['country_name'],
    locationmode='country names',
    colorscale='Portland',
    text=['Country'],
    z=revenue_per_country['iap_price_usd_cents'],
    colorbar={'title': 'Total revenue in $'}
))

# Horizontal bar chart showing top 10 countries by total users
# x - top 10 revenues
# y - their countries
bar_chart_data = go.Figure(go.Bar(
    x=revenue_per_country['iap_price_usd_cents'].nlargest(n=10),
    y=revenue_per_country['country_name'],
    hovertemplate='Total revenue: %{x}$, Country: %{y} <extra></extra>',
    marker=dict(color=revenue_per_country['iap_price_usd_cents'],
                colorscale='Portland'),
    orientation='h'))

# Preparing subplot grid and what types it will contain
subplot = make_subplots(rows=1, cols=2,
                        specs=[[{'type': 'choropleth'}, {'type': 'xy'}]])

# Add traces from figures to subplot
for trace in map_data.data:
    subplot.add_trace(trace, row=1, col=1)

for trace in bar_chart_data.data:
    subplot.add_trace(trace, row=1, col=2)

# Update and show layout of the Subplot
subplot.update_layout(title_text="Total revenue generated by each country in the year 2016",
                      yaxis={'categoryorder': 'total ascending'},
                      margin=dict(l=60, r=60, t=50, b=50))
subplot.show()
